### ISSUE TITLE
newline bug

### ISSUE THREAD

**Issue by atommixz** [agl/xmpp-client#124]
how can I fix it?
https://transfer.sh/jx9gw/2016-09-26-181152-1920x1080-scrot.png

this is tmux into mosh

**Comment by agl** [comment]
What's the terminal stack in use here? (I.e. what's the OS, terminal emulator and any terminal manager programs running?)

**Comment by atommixz** [comment]
Archlinux
```
echo $TERM
screen
```
tmux into mosh (http://mosh.mit.edu/)

**Comment by AkaBkn** [comment]
i had the same problem with different terminals, operating systems.
solution: replace all '\n' with '\r\n' in the source code.

**Comment by mutantmonkey** [comment]
I've run into this problem was well on Arch Linux and it appears to be independent of terminal emulator. I did not see it in a build of xmpp-client from January of this year, so I think that this bug may have been introduced with https://github.com/golang/crypto/commit/911fafb28f4ee7c7bd483539a6c96190bbbccc3f.

**Comment by agl** [comment]
Should be fixed by https://go-review.googlesource.com/#/c/33902/.
